### ISSUE TITLE
How to avoid logging in every time page reloads

### ISSUE THREAD

**Issue by gamedevsam** [theidealist/node-etrade-api#4]
Right now if I use the back button on my web app I have to re-log into ETrade every time. Any ideas on how I could store etrade token in a mongo database or session variable to reduce frequency of login prompt?

**Comment by theidealist** [comment]
Without knowing the details of your web app, it's tough to give you much direction here other than to say, yes, you can definitely do this.  Of course, it doesn't help that I wrote this code a long time ago.

I'd take a stab at it by looking at the code [here](https://github.com/theidealist/node-etrade-api/blob/master/lib/authorization.js#L132).  You can see the credentials are stored in the object's configuration, and handed to the success handler.  I imagine you can save and restore these three state variables to get the desired effect?  Keep in mind you have to renew your access token every so often.

When I was working on this more intensely, I remember I wrote something that kept my users logged in for a long time by setting up background jobs to renew their tokens periodically.  It shouldn't be too hard to do.

Good luck!
